services:
  - type: web
    name: me5-ir-command-tool
    runtime: node
    buildCommand: npm install
    startCommand: node server-admzip.js
    envVars:
      - key: NODE_ENV
        value: production
